# swiftlint 0.27.0

excluded:
  - Pods
  - CatchMe/Resources/Images/Images.swift
  - CatchMe/Resources/Localization/Localizable.swift
  - CatchMe/Application/CoreLayer/Common/Extensions/Container.swift
  - vendor

opt_in_rules:
#  - attributes
#  - closure_end_indentation
#  - closure_spacing
#  - conditional_returns_on_newline
#  - empty_count
#  - explicit_enum_raw_value
#  - explicit_init
#  - explicit_top_level_acl
#  - explicit_type_interface
#  - extension_access_modifier
#  - fatal_error_message
#  - file_header
#  - first_where
#  - force_unwrapping
#  - implicit_return
#  - implicitly_unwrapped_optional
#  - joined_default_parameter
#  - let_var_whitespace
#  - multiline_parameters
#  - nimble_operator
#  - no_extension_access_modifier
#  - no_grouping_extension
#  - number_separator
#  - object_literal
#  - operator_usage_whitespace
#  - overridden_super_call
#  - pattern_matching_keywords
#  - private_outlet
#  - prohibited_super_call
#  - quick_discouraged_call
#  - redundant_nil_coalescing
#  - single_test_class
#  - sorted_imports
#  - strict_fileprivate
#  - switch_case_on_newline
#  - trailing_closure
#  - unneeded_parentheses_in_closure_argument
#  - vertical_parameter_alignment_on_call

type_name:
    min_length: 2
    max_length: 54

function_body_length: 50
line_length: 150
file_length: 700

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 34
    error: 34
  excluded:
    - initialViewControllersTypes
cyclomatic_complexity:
  error: 30
